// Account:
export const SHOW_MODAL_ADD_ACCOUNT = "SHOW_MODAL_ADD_ACCOUNT";
export const HIDE_MODAL_ADD_ACCOUNT = "HIDE_MODAL_ADD_ACCOUNT";
export const SHOW_MODAL_UPDATE_ACCOUNT = "SHOW_MODAL_UPDATE_ACCOUNT";
export const HIDE_MODAL_UPDATE_ACCOUNT = "HIDE_MODAL_UPDATE_ACCOUNT";
export const FETCH_ACCOUNT_API = "FETCH_ACCOUNT_API";

// Product:
export const SHOW_MODAL_ADD_PRODUCT = "SHOW_MODAL_ADD_PRODUCT";
export const HIDE_MODAL_ADD_PRODUCT = "HIDE_MODAL_ADD_PRODUCT";
export const SHOW_MODAL_UPDATE_PRODUCT = "SHOW_MODAL_UPDATE_PRODUCT";
export const HIDE_MODAL_UPDATE_PRODUCT = "HIDE_MODAL_UPDATE_PRODUCT";
export const FETCH_PRODUCT_API = "FETCH_PRODUCT_API";
export const FETCH_MANUFACTURER_API = "FETCH_MANUFACTURER_API";
export const FETCH_CATEGORY_API = "FETCH_CATEGORY_API";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SHOW_UPDATE_PRODUCT = "SHOW_UPDATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

// Order Product:
export const ADD_ORDER_PRODUCT = "ADD_ORDER_PRODUCT";
export const DELETE_ORDER_PRODUCT = "DELETE_ORDER_PRODUCT";
export const INCREASE_ORDER_PRODUCT = "INCREASE_ORDER_PRODUCT";
export const DECREASE_ORDER_PRODUCT = "DECREASE_ORDER_PRODUCT";
